---
title: "TidyTemplate for modelling"
date: 2020-09-07
output: html_output
editor_options: 
  chunk_output_type: console
---

# TidyTuesday

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE, cache = TRUE, warning = FALSE, message = FALSE,
                      dpi = 180, fig.width = 8, fig.height = 5)

library(tidyverse)
library(tidytuesdayR)
library(tidymodels)
theme_set(theme_light())
```

# Download the weekly Data

Dowload the weekly data and make available in the `tt` object.

```{r Load}

tt <- tt_load("2020-09-01")
tt

```

Loadin the raw data
```{r}
key_crop_yield_raw <- tt$key_crop_yields
arable_land_raw <- tt$arable_land_pin
fertilizer_raw <- tt$cereal_crop_yield_vs_fertilizer_application
land_use_raw <- tt$land_use_vs_yield_change_in_cereal_production
tractor_raw <- tt$cereal_yields_vs_tractor_inputs_in_agriculture
```

# Clean the data

```{r Wrangle}

key_crop_yield <- key_crop_yield_raw %>% 
    janitor::clean_names() %>% 
    rename_all(str_remove, "_tonnes.*")
    
arable_land <- arable_land_raw %>% 
    janitor::clean_names() %>% 
    rename(arable_land_needed = 4)

fertilizer <- fertilizer_raw %>% 
    rename(yield = 4,
           fertilizer_use = 5)

land_use <- land_use_raw %>% 
    janitor::clean_names() 
```

```{r}
top_countries <- land_use %>% 
    filter(!is.na(code),
           entity != "World") %>% 
    group_by(entity) %>% 
    filter(year == max(year)) %>% 
    ungroup() %>% 
    arrange(desc(total_population_gapminder)) %>% 
    head(30) %>% 
    pull(entity)

```

```{r}
yield_tidy <- key_crop_yield %>% 
    pivot_longer(wheat:bananas, names_to = "crop", values_to = "yield") %>% 
    filter(!is.na(yield),
           crop %in% c("wheat", "maize", "barley", "rice"),
           entity %in% top_countries)
```


```{r}
yield_tidy %>% 
    ggplot(aes(year, yield, color = crop)) +
    geom_line(size = 1, alpha = 0.5) +
    geom_point() +
    facet_wrap(~entity, scales = "free_y") +
    labs(x = "",
         y = "yield (tonnes per hectare)")
```

```{r}
yield_tidy %>% 
    ggplot(aes(year, yield, color = entity)) +
    geom_line(size = 1, alpha = 0.5) +
    facet_wrap(~crop, scales = "free_y") +
    labs(x = "",
         y = "yield (tonnes per hectare)")
```


```{r}
tidy_lm <- yield_tidy %>% 
    nest(yields = c(year, yield)) %>% 
    mutate(model = map(yields, ~lm(yield~year, data = .x)))

slopes <- tidy_lm %>% 
    mutate(coefs = map(model, tidy)) %>% 
    unnest(coefs) %>% 
    filter(term == "year") %>% 
    mutate(p.value = p.adjust(p.value))

```

### Lets visualize these results

```{r}
slopes %>% 
    ggplot(aes(estimate, p.value)) +
    geom_point(aes(color = crop), show.legend = F, size = 2) +
    geom_vline(xintercept = 0, size = 1, lty = 2, color = "gray50") +
    geom_text(aes(label = entity), check_overlap = T, vjust = 1, hjust =1, show.legend = F, size = 2.5) +
    facet_wrap(~crop) +
    scale_y_log10()
```














