---
title: 'Our World in Data: Crop Yields'
author: "Gaurav Sharma"
date: "07/09/2020"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r}
library(dplyr)
library(ggplot2)
library(forcats)
library(shiny)
library(stringr)
library(plotly)
theme_set(theme_light())
```

```{r}
yields_tidy <- readRDS("yields_tidy.rds")

top_crops <- yields_tidy %>%
  count(crops, sort = TRUE) %>%
  head(9) %>%
  pull(crops)

```

```{r}
# plot_yields <-  function(tbl) {
#   tbl %>%
#     mutate(crops = fct_reorder(crops, -yield)) %>%
#     ggplot(aes(year, yield, color = crops)) +
#     geom_line(size = 1) +
#     facet_wrap(~entity) +
#     labs(
#       x = "Year",
#       y = "Yield (tonnes per hectare)",
#       title = "Crops yields over time in US",
#       subtitle = "Data from Our World in Data"
#     )
# }

# yields_tidy %>% 
#   filter(entity == "United States") %>% 
#   plot_yields()


plot_yields <- function(tbl, facet_scales = "fixed") {
  g <- tbl %>%
    mutate(crops = fct_reorder(crops, -yield)) %>%
    mutate(entity = fct_reorder(entity, -yield)) %>%
    ggplot(aes(year, yield, color = entity)) +
    geom_line() +
    expand_limits(y = 0) +
    facet_wrap(~ crops, scales = facet_scales) +
    labs(x = "Year",
         y = "Yield (tonnes per hectare)",
         title = "Crop yields over time",
         color = "Country")
  
  ggplotly(g)
}
# yields_tidy %>%
#   filter(code %in% c("USA", "IND")) %>%
#   plot_yields()
```

## Inputs and Outputs

```{r ,echo=FALSE}
# inputPanel(
#   selectInput("entity", label = "Country",
#               choices = unique(yields_tidy$entity), 
#               selected = "India",
#               multiple = TRUE)
# )
# 
# 
# renderPlot({
#   yields_tidy %>% 
#     filter(entity %in% input$entity) %>% 
#     plot_yields()
# 
# })

inputPanel(
  selectInput("entity",
              label = "Country/Continent/Region:",
              choices = unique(yields_tidy$entity),
              selected = c("United States", "India"),
              selectize = TRUE,
              multiple = TRUE),
  selectInput("crops",
              label = "Crops:",
              choices = unique(yields_tidy$crop),
              selected = top_crops,
              selectize = TRUE,
              multiple = TRUE),
  radioButtons("facet_scales",
               label = "",
               choices = c("Free y-axis" = "free_y",
                           "Shared y-axis" = "fixed"))
)
renderPlotly({
  yields_tidy %>%
    filter(entity %in% input$entity,
           crops %in% input$crops) %>%
    plot_yields(facet_scales = input$facet_scales)
})

```
